<a href="https://colab.research.google.com/github/i-ganza007/ML_Exercises/blob/main/PoorNeuralNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [47]:
data = pd.read_csv('/content/car_purchasing.csv', encoding='latin1')
data

       customer name  ... car purchase amount
0      Martina Avila  ...         35321.45877
1      Harlan Barnes  ...         45115.52566
2    Naomi Rodriquez  ...         42925.70921
3    Jade Cunningham  ...         67422.36313
4       Cedric Leach  ...         55915.46248
..               ...  ...                 ...
495           Walter  ...         48901.44342
496            Vanna  ...         31491.41457
497            Pearl  ...         64147.28888
498             Nell  ...         45442.15353
499            Marla  ...         45107.22566

[500 rows x 9 columns]

In [48]:
print(data['country'].unique().shape,data['customer e-mail'].value_counts())

(211,) customer e-mail
Camaron.marla@hotmail.com                                     1
cubilia.Curae.Phasellus@quisaccumsanconvallis.edu             1
eu.dolor@diam.co.uk                                           1
vulputate.mauris.sagittis@ametconsectetueradipiscing.co.uk    1
sem.Pellentesque@quis.net                                     1
                                                             ..
Phasellus@sedsemegestas.org                                   1
nunc.est.mollis@Suspendissetristiqueneque.co.uk               1
vehicula@at.co.uk                                             1
mi@Aliquamerat.edu                                            1
felis.ullamcorper.viverra@egetmollislectus.net                1
Name: count, Length: 500, dtype: int64

In [49]:
data.isna().sum()

customer name          0
customer e-mail        0
country                0
gender                 0
age                    0
annual Salary          0
credit card debt       0
net worth              0
car purchase amount    0
dtype: int64

In [50]:
data.isnull().sum()

customer name          0
customer e-mail        0
country                0
gender                 0
age                    0
annual Salary          0
credit card debt       0
net worth              0
car purchase amount    0
dtype: int64

In [51]:
data['country'].unique()

array(['Bulgaria', 'Belize', 'Algeria', 'Cook Islands', 'Brazil',
       'Liberia', 'Syria', 'Czech Republic', 'Armenia', 'Somalia',
       'Sint Maarten', 'Greenland', 'Nicaragua', 'Palestine, State of',
       'United Arab Emirates', 'Gabon', 'Tokelau', 'Portugal', 'Chad',
       'Iraq', 'Sudan', 'Angola', 'Nigeria', 'Madagascar', 'Macedonia',
       'Oman', 'Colombia', 'Namibia', 'Denmark', 'Dominican Republic',
       'Costa Rica', 'Botswana', 'Saint Pierre and Miquelon', 'France',
       'Senegal', 'Cambodia', 'Suriname', 'Turkey', 'Ethiopia',
       'French Guiana', 'Bhutan', 'Georgia', 'Mozambique', 'Nauru',
       'Timor-Leste', 'Djibouti', 'Argentina', 'Taiwan', 'Åland Islands',
       'Turks and Caicos Islands', 'Samoa', 'Vanuatu', 'Mongolia',
       'Sri Lanka', 'Guinea-Bissau', 'Egypt', 'Slovenia', 'Benin',
       'Cape Verde', 'Paraguay', 'Laos', 'Iceland', 'Viet Nam',
       'Marshall Islands', 'Germany', 'Kyrgyzstan', 'Mauritius', 'Gambia',
       'Reunion', 'Jordan', 'Slovakia', 'Kiribati',
       'United States Minor Outlying Islands', 'Puerto Rico', 'Guinea',
       'Guam', 'China', 'Sierra Leone', 'Ecuador', 'Anguilla',
       'Kazakhstan', 'Jersey', 'Macao', 'Indonesia', 'Palau', 'Ghana',
       'Cameroon', 'Myanmar', 'Central African Republic', 'Bolivia',
       'Tuvalu', 'Qatar', 'Venezuela', 'Togo', 'Nepal', 'Saudi Arabia',
       'San Marino', 'Saint Lucia', 'Solomon Islands', 'Andorra',
       'Falkland Islands', 'Japan', 'Israel', 'Christmas Island',
       'Liechtenstein', 'Mayotte', 'Saint Kitts and Nevis', 'Maldives',
       'Aruba', 'Lebanon', 'Monaco', 'Martinique', 'Guadeloupe',
       'Equatorial Guinea', 'South Africa', 'Wallis and Futuna',
       'Tunisia', 'Pakistan', 'Bahrain', 'Serbia', 'Peru', 'Austria',
       'Lithuania', 'Curaçao', 'Zimbabwe', 'Uganda', 'Kenya', 'Kuwait',
       'Greece', 'Bouvet Island', 'Thailand', 'Bahamas', 'Latvia',
       'Hong Kong', 'French Polynesia', 'Yemen',
       'Heard Island and Mcdonald Islands', 'Virgin Islands, British',
       'Singapore', 'Cocos (Keeling) Islands', 'Saint Martin',
       'Northern Mariana Islands', 'Croatia', 'Malta', 'Mauritania',
       'Guyana', 'Haiti', 'Faroe Islands', 'Saint Barthélemy', 'Poland',
       'Congo (Brazzaville)', 'Guernsey', 'Sao Tome and Principe',
       'Grenada', 'United States', 'Virgin Islands, United States',
       'Bermuda', 'Norfolk Island', 'Italy', 'Bangladesh', 'Philippines',
       'French Southern Territories', 'Jamaica', 'Belarus',
       'Turkmenistan', 'Guatemala', 'Saint Vincent and The Grenadines',
       'Tonga', 'Papua New Guinea', 'Canada',
       'Bonaire, Sint Eustatius and Saba', 'El Salvador', 'Isle of Man',
       'Bosnia and Herzegovina', 'India', 'Trinidad and Tobago',
       'Moldova', 'Tanzania', 'Niue', 'Rwanda', 'Morocco',
       'Western Sahara', 'Micronesia', 'American Samoa',
       'United Kingdom (Great Britain)', 'Seychelles', 'Switzerland',
       'Chile', 'Uruguay', 'South Georgia and The South Sandwich Islands',
       'Afghanistan', 'Belgium', 'Antarctica', 'Korea, South',
       'Cayman Islands', 'Honduras', 'Mexico', 'Australia', 'Montenegro',
       'Luxembourg', 'Hungary', 'Niger', 'New Caledonia', 'Mali',
       'Malawi', 'South Sudan', 'Ukraine', 'New Zealand',
       'Saint Helena, Ascension and Tristan da Cunha', 'Malaysia',
       'marlal'], dtype=object)

In [52]:
data.drop(columns=['country','customer e-mail','customer name'],inplace=True,axis=1)
data

     gender        age  ...    net worth  car purchase amount
0         0  41.851720  ...  238961.2505          35321.45877
1         0  40.870623  ...  530973.9078          45115.52566
2         1  43.152897  ...  638467.1773          42925.70921
3         1  58.271369  ...  548599.0524          67422.36313
4         1  57.313749  ...  560304.0671          55915.46248
..      ...        ...  ...          ...                  ...
495       0  41.462515  ...  541670.1016          48901.44342
496       1  37.642000  ...  360419.0988          31491.41457
497       1  53.943497  ...  764531.3203          64147.28888
498       1  59.160509  ...  337826.6382          45442.15353
499       1  46.731152  ...  462946.4924          45107.22566

[500 rows x 6 columns]

In [57]:
X = data.drop(columns=['car purchase amount'],axis=1)
y = data['car purchase amount']

In [71]:
X

     gender        age  annual Salary  credit card debt  net worth
0         0  41.851720       0.058576          0.574271  -1.110469
1         0  40.870623       0.386570         -0.009951   0.573929
2         1  43.152897      -0.712361          0.445452   1.193976
3         1  58.271369       1.474794          1.382369   0.675595
4         1  57.313749      -0.205111         -1.218962   0.743113
..      ...        ...            ...               ...        ...
495       0  41.462515       0.839501         -0.749274   0.635628
496       1  37.642000      -0.520691          0.772819  -0.409872
497       1  53.943497       0.578321          0.288023   1.921144
498       1  59.160509      -1.053335          1.263847  -0.540190
499       1  46.731152      -0.064709         -0.062055   0.181531

[500 rows x 5 columns]

In [72]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: car purchase amount, Length: 500, dtype: float64

In [76]:
x_train , x_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [77]:
x_train

     gender        age  annual Salary  credit card debt  net worth
249       0  36.117247       0.701969          0.061845   1.160136
433       1  39.814817      -0.516675         -0.866122  -1.171455
19        0  58.741842      -0.578104          1.051526   0.776096
322       0  60.180119      -0.281334          0.912635   1.100863
332       0  31.244838      -1.776076          0.329307   1.062765
..      ...        ...            ...               ...        ...
106       0  41.796014      -0.945270          0.805923   0.109173
270       0  35.375156      -2.455102         -0.297511  -1.270784
348       0  45.305941       0.122635         -1.686184   1.018348
435       1  57.974293      -1.772026         -0.400581  -0.058586
102       1  30.492353       0.527037         -0.645454  -0.155849

[400 rows x 5 columns]

In [78]:
y_train

249    46135.27233
433    29519.56184
19     54827.52403
322    59625.02618
332    25252.93221
          ...
106    34803.82395
270    12536.93842
348    49348.88394
435    42139.64528
102    33640.73697
Name: car purchase amount, Length: 400, dtype: float64

In [79]:
scaler = StandardScaler()
cols = ['annual Salary','annual Salary','net worth']
data_scaled = scaler.fit_transform(x_train[cols])
x_train[cols] = data_scaled
x_train

     gender        age  annual Salary  credit card debt  net worth
249       0  36.117247       0.702645          0.061845   1.143221
433       1  39.814817      -0.495836         -0.866122  -1.161885
19        0  58.741842      -0.556249          1.051526   0.763544
322       0  60.180119      -0.264389          0.912635   1.084622
332       0  31.244838      -1.734400          0.329307   1.046957
..      ...        ...            ...               ...        ...
106       0  41.796014      -0.917339          0.805923   0.104197
270       0  35.375156      -2.402191         -0.297511  -1.260085
348       0  45.305941       0.132896         -1.686184   1.003044
435       1  57.974293      -1.730417         -0.400581  -0.061657
102       1  30.492353       0.530608         -0.645454  -0.157814

[400 rows x 5 columns]

In [80]:
import tensorflow as tf

In [89]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(5,input_shape=(5,),activation='relu'),
    tf.keras.layers.Dense(50,activation='relu'),
    tf.keras.layers.Dense(100,activation='relu'),
    tf.keras.layers.Dense(150,activation='relu'),
    tf.keras.layers.Dense(1,activation='linear')
])

model.compile(optimizer='adam',loss='mse',metrics=['mse'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 50)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 100)            │         5,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 150)            │        15,150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │           151 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 20,731 (80.98 KB)

 Trainable params: 20,731 (80.98 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
x_train.shape

(400, 5)

In [83]:
y_train.shape

(400,)

In [90]:
model.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1998515328.0000 - mse: 1998515328.0000
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2009242624.0000 - mse: 2009242624.0000
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2050093952.0000 - mse: 2050093952.0000
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2007158656.0000 - mse: 2007158656.0000
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2026191232.0000 - mse: 2026191232.0000
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1915029504.0000 - mse: 1915029504.0000
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1883921536.0000 - mse: 1883921536.0000
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1624065792.0000 - mse: 1624065792.0000
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1309895168.0000 - mse: 1309895168.0000
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 921118272.0000 - mse: 921118272.0000
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 439735392.0000 - mse: 439735392.0000
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 118697712.0000 - mse: 118697712.0000
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 58372620.0000 - mse: 58372620.0000
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 68702920.0000 - mse: 68702920.0000
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55394360.0000 - mse: 55394360.0000
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54345592.0000 - mse: 54345592.0000
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 61886612.0000 - mse: 61886612.0000
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55291796.0000 - mse: 55291796.0000
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54831496.0000 - mse: 54831496.0000
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 55890580.0000 - mse: 55890580.0000
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50731152.0000 - mse: 50731152.0000
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53582724.0000 - mse: 53582724.0000
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 51476412.0000 - mse: 51476412.0000
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53062496.0000 - mse: 53062496.0000
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50948428.0000 - mse: 50948428.0000
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 48309992.0000 - mse: 48309992.0000
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 54754780.0000 - mse: 54754780.0000
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53505128.0000 - mse: 53505128.0000
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50266124.0000 - mse: 50266124.0000
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 45342244.0000 - mse: 45342244.0000
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47241944.0000 - mse: 47241944.0000
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 46949532.0000 - mse: 46949532.0000
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50757268.0000 - mse: 50757268.0000
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 44903056.0000 - mse: 44903056.0000
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 47736516.0000 - mse: 47736516.0000
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 48476016.0000 - mse: 48476016.0000
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 43832520.0000 - mse: 43832520.0000
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45329504.0000 - mse: 45329504.0000
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 41350092.0000 - mse: 41350092.0000
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42808876.0000 - mse: 42808876.0000
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42229856.0000 - mse: 42229856.0000
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42184764.0000 - mse: 42184764.0000
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 40565556.0000 - mse: 40565556.0000
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 40103740.0000 - mse: 40103740.0000
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 38061712.0000 - mse: 38061712.0000
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 39620512.0000 - mse: 39620512.0000
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 38026884.0000 - mse: 38026884.0000
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35673348.0000 - mse: 35673348.0000
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 37078872.0000 - mse: 37078872.0000
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35804436.0000 - mse: 35804436.0000
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37174920.0000 - mse: 37174920.0000
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31399200.0000 - mse: 31399200.0000
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30465614.0000 - mse: 30465614.0000
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 31492016.0000 - mse: 31492016.0000
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31235160.0000 - mse: 31235160.0000
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34378852.0000 - mse: 34378852.0000
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31812000.0000 - mse: 31812000.0000
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34344088.0000 - mse: 34344088.0000
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30498564.0000 - mse: 30498564.0000
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28479664.0000 - mse: 28479664.0000
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 29696452.0000 - mse: 29696452.0000
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28969134.0000 - mse: 28969134.0000
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28059898.0000 - mse: 28059898.0000
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28778906.0000 - mse: 28778906.0000
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28426874.0000 - mse: 28426874.0000
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26556124.0000 - mse: 26556124.0000
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25882248.0000 - mse: 25882248.0000
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25048156.0000 - mse: 25048156.0000
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23212106.0000 - mse: 23212106.0000
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22475930.0000 - mse: 22475930.0000
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23165942.0000 - mse: 23165942.0000
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22658566.0000 - mse: 22658566.0000
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20496042.0000 - mse: 20496042.0000
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19658024.0000 - mse: 19658024.0000
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19839710.0000 - mse: 19839710.0000
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19813848.0000 - mse: 19813848.0000
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18749410.0000 - mse: 18749410.0000
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18290288.0000 - mse: 18290288.0000
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17949852.0000 - mse: 17949852.0000
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16031024.0000 - mse: 16031024.0000
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16203020.0000 - mse: 16203020.0000
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15932131.0000 - mse: 15932131.0000
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15259027.0000 - mse: 15259027.0000
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13498397.0000 - mse: 13498397.0000
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11649707.0000 - mse: 11649707.0000
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13711098.0000 - mse: 13711098.0000
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11816106.0000 - mse: 11816106.0000
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10882839.0000 - mse: 10882839.0000
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11126486.0000 - mse: 11126486.0000
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10740990.0000 - mse: 10740990.0000
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10684705.0000 - mse: 10684705.0000
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7834204.0000 - mse: 7834204.0000
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8919014.0000 - mse: 8919014.0000
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7190388.5000 - mse: 7190388.5000
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7391114.0000 - mse: 7391114.0000
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7091823.0000 - mse: 7091823.0000
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6326960.0000 - mse: 6326960.0000
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5975460.0000 - mse: 5975460.0000
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5703135.5000 - mse: 5703135.5000
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5443627.0000 - mse: 5443627.0000